### ISSUE TITLE
Screen Off issue

### ISSUE THREAD

**Issue by turbo159** [grzegorz914/homebridge-lgwebos-tv#177]
Hi, great plugin.  However, screen off/on doesn't seem to work for me.  Screen On works if I manually turn off the screen.  Screen off does not.  The plug-in is able to see the current state when I control the on/off manually.  Other controls do work such as TV on/off, or input switching.

 -------- LGTV --------
Manufacturer: LG Electronics
Model: OLED65C8AUA
System: webOSTV 4.0
Firmware: 05.50.15

**Comment by Fookes74** [comment]
Funnily enough, I came on here to report that I have the exact opposite issue. Mine will reliably turn off but will not turn on at all. The tile lights up to signify it's on but it doesn't actually do it. I've always just wanted the plugin for on/off controls but I also note that despite removing all options for showing inputs / channels, it still shows them in the tile. I'm fairly sure a version of this plugin I used previously didn't have this.

It's frustrating and I have no idea of what to do to fix this issue turning the TV on. I had this plugin (or a version of) working perfectly previously. Sadly I inadvertently trashed a backup I had and following a requirement to rebuild Homebridge I'm now unable to get it working properly again. 

LGTV

Manufacturer: LG Electronics
Model: 55UB850V-ZD
System: webOS 2.4.1
Firmware: 5.6.10

**Comment by grzegorz914** [comment]
@Fookes74 
can you post debut during try to power on.

**Comment by Fookes74** [comment]
> @Fookes74
> can you post debut during try to power on.

Sure can. This is what I'm seeing when I enabled debug:

![Screenshot 2023-11-01 at 11 55 52](https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/37369430/7cde1e6c-a8fb-41e5-9868-37c00c051177)

![Screenshot 2023-11-01 at 11 56 21](https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/37369430/a41d2394-14f8-4e04-b0d1-42839dfc6d64)

Yet again, inputs show even though I've not selected them in the config. TV powers off without issue. Just won't turn on even though tile (eventually) shows it as being on. I usually get a spinning circle in the tile like its processing.

**Comment by grzegorz914** [comment]
The tv is powered od over Wake On Lan are you sure You have set correct Mac Address in plugin config?

**Comment by Fookes74** [comment]
> The tv is powered od over Wake On Lan are you sure You have set correct Mac Address in the plugin config?

Yep. TV settings show wifi and wired MAC addresses. Checked and double-checked. My TV is connected via ethernet so I'm using the wired MAC address. Unless there's a specific way I'm meant to input it in to the config? I'm doing it like this:

xx:12:xx:34:xx:56

**Comment by grzegorz914** [comment]
yes, it is correct address, check please tv settings to have enabled possibility  power on over lan,
https://www.lg.com/au/support/product-help/CT20088015-1437132986635

regarding load inputs even are not configured, I have prepared 2.14.0-beta.0 with possibility to disable load default inputs, its configured in plugin settings >>> inputs>>> disable load default inputs, check this please and let me know

**Comment by Fookes74** [comment]
> yes, it is correct address, check please tv settings to have enabled possibility power on over lan, https://www.lg.com/au/support/product-help/CT20088015-1437132986635

**LG Connect is configured and request accepted when plugin installed. It's not that - at least on the face of it.**
> 
> regarding load inputs even are not configured, I have prepared 2.14.0-beta.0 with possibility to disable load default inputs, its configured in plugin settings >>> inputs>>> disable load default inputs, check this please and let me know

I'll check out the beta version (if that's what you mean) and see if I can disable the inputs. Fundamentally though, they are secondary compared to the on/off issues for me.

Note: I've redone LG Connect and now the home app tile shows on and off but TV will not turn on or off at all!

**Comment by grzegorz914** [comment]
Can you enable TV using LG connect app or other external app?
beta.1 with fixed inputs published, try and let me know

**Comment by grzegorz914** [comment]
@turbo159 

can you try 2.14.0-beta.2 and let me know

**Comment by Fookes74** [comment]
> @turbo159
> 
> can you try 2.14.0-beta.2 and let me know

Sorry - had to pop out. I've updated to latest beta version. It now disables the option of inputs successfully. I completely wiped the 'pair accessories' part of LG connect and then accepted the invite to connect once I'd restarted homebridge. Sadly, it turns on and off for the tile but doesn't do anything on the TV. This is the output from the logs in Homebridge:

![Screenshot 2023-11-01 at 17 03 46](https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/37369430/0fec297a-5b65-4d8e-afb7-780ad4473214)

**Comment by grzegorz914** [comment]
@turbo159 
can you post whole debug log direct after restart the plugin?

**Comment by Fookes74** [comment]
> @turbo159
> can you post whole debug log direct after restart the plugin?

Apologies - I've just spotted that you're tagging the person who posted the original issue. I take it you're actually responding to me? If so, can you tell me what I need to do to get the whole debug log direct?

**Comment by grzegorz914** [comment]
@Fookes74 
the whole log file You can download from Homebridge Config  UI

**Comment by Fookes74** [comment]
> @Fookes74
> the whole log file You can download from Homebridge Config UI

Sure:

[homebridge.log-2.txt](https://github.com/grzegorz914/homebridge-lgwebos-tv/files/13230248/homebridge.log-2.txt)

**Comment by grzegorz914** [comment]
install beta.7 and get the log again

**Comment by Fookes74** [comment]
> install beta.7 and get the log again

Here:

[homebridge.log.txt](https://github.com/grzegorz914/homebridge-lgwebos-tv/files/13230768/homebridge.log.txt)

**Comment by Fookes74** [comment]
> > install beta.7 and get the log again
> 
> Here:
> 
> [homebridge.log.txt](https://github.com/grzegorz914/homebridge-lgwebos-tv/files/13230768/homebridge.log.txt)

****UPDATE**** Tried using beta 7. It turned tv off (then flipped between showing 'off' in tile to 'on' and then wouldn't control turning TV on - only working for 'off'). Continuing to get whirring 'processing' circle when flitting between on and off on tile.

**Comment by Fookes74** [comment]
> install beta 8 try on off few times and get the log again

updated to beta 8. Tried off and on several times. Visually, exactly the same. 'off' works immediately. 'on' doesn't work at all.  Here's the log taken after a few goes of 'off' and 'on':

[homebridge.log.txt](https://github.com/grzegorz914/homebridge-lgwebos-tv/files/13230935/homebridge.log.txt)

**Comment by grzegorz914** [comment]
please install beta.9 and describe what not working, also please post the log again

**Comment by Fookes74** [comment]
> please install beta.9 and describe what not working, also please post the log again

Same. On beta 9. Turns off TV instantly. When trying to turn on it goes to 'on' for a moment in the tile (with the whirring icon) and then turns itself off. TV itself doesn't respond and won't turn on. If I repeatedly press on and off nothing happens. Occasionally get the whirring cog and sometimes I don't. Interestingly, tile seems to recognise state. It was showing as off on tile until I turned the TV on via TV remote. Whilst it wasn't instant it changed the tile to 'on' after a few seconds. Here's the log:

[homebridge.log.txt](https://github.com/grzegorz914/homebridge-lgwebos-tv/files/13231261/homebridge.log.txt)

**Comment by grzegorz914** [comment]
You can not power on because your tv doesn’t respond to wake on lan packet, Can you power on TV using LG connect app or other external app?

**Comment by Fookes74** [comment]
> You can not power on because your tv doesn’t respond to wake on lan packet, Can you power on TV using LG connect app or other external app?

I had this plugin (or a variant of it) working perfectly until recently when I had to start from scratch. It powered the tv on and off without issue, immediately both ways for months and months. I know the TV can work with a variant of the webOS plugin because it has. 
I'll try with the LG app but won't be able to do this until tomorrow morning now. I'll report back in the morn. Appreciate your help.

**Comment by grzegorz914** [comment]
OK, check this please and let me know, looks like the packet is not received by tv, may be you have something changed in the tv settings or in your local network.

**Comment by Fookes74** [comment]
> > You can not power on because your tv doesn’t respond to wake on lan packet, Can you power on TV using LG connect app or other external app?
> 
> I had this plugin (or a variant of it) working perfectly until recently when I had to start from scratch. It powered the tv on and off without issue, immediately both ways for months and months. I know the TV can work with a variant of the webOS plugin because it has. I'll try with the LG app but won't be able to do this until tomorrow morning now. I'll report back in the morn. Appreciate your help.

UPDATE - I managed to quickly download the LG thinQ app (couldn't find the LG Connect app - am in UK). This behaves similarly. I can turn off the TV instantly but the power button then disappears from app so can't turn on from there. 

It seems to be a TV issue therefore but its ridiculous as I know this can and HAS worked flawlessly. I have reset and reconnected the LG Connect setting with the plugin multiple times so it sees the plugin without issue.

**Comment by Fookes74** [comment]
> OK, check this please and let me know, looks like the packet is not received by tv, may be you have something changed in the tv settings or in your local network.

See my updated response. I haven't changed any of the TV settings at all. Nothing. In terms of network changes, all that has changed is that the homebridge which was working with this plugin was run on a raspberry pi and my present instance is running in a Docker Container with its own IP address on a HP EliteDesk SFF PC.

**Comment by grzegorz914** [comment]
Are you sure you can send WoL broadcast packet from this IP to TV, may be firewall

**Comment by Fookes74** [comment]
> Are you sure you can send WoL broadcast packet from this IP to TV, may be firewall

I have no idea tbh. My knowledge on docker, containers etc, is very limited. I sought help in configuring all of this. I presumed that if its able to turn it off then it should be able to communicate similarly to turn it on, or is that not how it works?

**Comment by grzegorz914** [comment]
The communication between tv and plugin is over WebSocket and this working correct but power on TV is realized over Wake On LAN broadcast packet and port 9, and looks like here is problem. 

Look here, looks like you can not send Wake On LAN packet from inside the docker container
https://www.reddit.com/r/selfhosted/comments/121pxol/wake_on_lan_gui_on_docker_container/?rdt=62783

**Comment by Fookes74** [comment]
> https://www.reddit.com/r/selfhosted/comments/121pxol/wake_on_lan_gui_on_docker_container/?rdt=62783

I was hoping you were not going to say that! I greatly appreciate your help on this. I found this article which seems to suggest it's possible. Whilst I certainly don't understand fully what it's telling me here, it suggests the plugin for the users Tizen TV utilises a wol: IPADDRESS as part of the plugin config in homebridge. Can you make sense of what it is saying?

**Comment by grzegorz914** [comment]
Yes, it is possible but all on both side need to be adapted

**Comment by Fookes74** [comment]
> Yes, it is possible but all on both side need to be adapted

Should I be posing this question on another forum for assistance?

**Comment by grzegorz914** [comment]
Yes You can, I don’t have docker in my environment.

**Comment by Fookes74** [comment]
> Yes You can, I don’t have docker in my environment.

Ok. Thanks for your assistance again.

**Comment by turbo159** [comment]
> @turbo159
> 
> can you try 2.14.0-beta and let me know

Hi.  Sorry I have been away.  I just tried the beta, but same issue.  I can turn the screen off, but it won't turn on.  I turned on debug mode.  I'm not sure I did it right since the logs look the same:  
<img width="929" alt="image" src="https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/25274813/8afe7ad9-e2f9-4d27-9831-d9988f8486b3">

**Comment by grzegorz914** [comment]
@turbo159 
debug mode can be enabled is in plugin settings Advanced Section >>>System>>>Debug Mode set it to true, save and restart the plugin.

**Comment by turbo159** [comment]
Cool thanks.  Ok, looks like debug does show an error:
<img width="1481" alt="image" src="https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/25274813/38db15c6-3230-4d2e-b92d-74594229bb51">

**Comment by grzegorz914** [comment]
The error  normal behavior, can you post whole debug log file during try to change screen state? it can be downloaded from Config UI X ?

**Comment by turbo159** [comment]
This is the debug file...
[homebridge.log-4.txt](https://github.com/grzegorz914/homebridge-lgwebos-tv/files/13241759/homebridge.log-4.txt)

**Comment by badgertastic** [comment]
12.4 broke screen off for me. Back on 12.13.4.

**Comment by grzegorz914** [comment]
On is working?

**Comment by badgertastic** [comment]
Neither on or off work. WebOS 5.0. Firmware 4.50.51
![IMG_0272](https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/17163432/b5948de8-ecf6-4117-ad64-7f1316774444)

**Comment by badgertastic** [comment]
With it working on 12.13.4
![IMG_0273](https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/17163432/7babcbc9-0539-4b62-ada5-cfad23e82936)

**Comment by grzegorz914** [comment]
@badgertastic 
please try 2.14.1-beta.0 and let me know

**Comment by turbo159** [comment]
I tried the latest beta, v2.14.1-beta0, and the screen off still didn't work for me: 

[11/5/2023, 6:18:00 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: Live TV, Reference: com.webos.app.livetv
[11/5/2023, 6:18:03 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/5/2023, 6:18:03 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Received message type: error, id: 2d5d5b30000f, data: {
  "returnValue": false,
  "state": "Active",
  "errorCode": "-102",
  "errorText": "The current state must be 'Screen Off'"

**Comment by turbo159** [comment]
Screen on used to work, but it doesn't work for me any more:

2023, 8:12:06 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen ON.
[11/5/2023, 8:12:06 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Received message type: error, id: da621dde0011, data: {}

**Comment by turbo159** [comment]
With the beta, trying to turn the screen on doesn't work on a single press, but when I turn it off again on the HomeKit button, it turn on even though the button shows off.  The state of the button is correct if you refresh the HomeKit screen.

[11/6/2023, 9:05:58 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen ON.
[11/6/2023, 9:05:58 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Received message type: error, id: 974aa0570015, data: {}
[11/6/2023, 9:06:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/6/2023, 9:06:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Screen Off",
  "processing": "Screen On"
}
[11/6/2023, 9:06:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Received message type: response, id: 5008c5360016, data: {
  "returnValue": true,
  "state": "Active"
}
[11/6/2023, 9:06:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/6/2023, 9:06:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/6/2023, 9:06:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Received message type: error, id: 2130d5cc0017, data: {
  "returnValue": false,
  "state": "Active",
  "errorCode": "-102",
  "errorText": "The current state must be 'Screen Off'"
}
[11/6/2023, 9:06:01 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 9:06:01 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[1

**Comment by grzegorz914** [comment]
try beta 1 and get the log again

**Comment by turbo159** [comment]
Ok beta2 restored screen on.  Screen off doesn't work.  When do screen off through the LG remote, there is a 5s countdown on the TV screen.  Does that make any difference?

[11/6/2023, 10:13:15 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen ON.
[11/6/2023, 10:13:15 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Screen Off",
  "processing": "Screen On"
}
[11/6/2023, 10:13:15 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/6/2023, 10:13:15 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/6/2023, 10:13:16 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 10:13:16 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 10:13:21 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 10:13:21 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 10:13:23 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/6/2023, 10:13:23 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {}
[11/6/2023, 10:13:26 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 10:13:26 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.

**Comment by grzegorz914** [comment]
try beta 3 and please also change volume, mute and input using HomeKit app and get the log again

**Comment by turbo159** [comment]
Beta5:
ScreenOff:
[11/6/2023, 11:06:10 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen ON.
[11/6/2023, 11:06:10 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Screen Off",
  "processing": "Screen On"
}
[11/6/2023, 11:06:10 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/6/2023, 11:06:10 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/6/2023, 11:06:12 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 11:06:12 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 11:06:17 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 11:06:17 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 11:06:18 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/6/2023, 11:06:18 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {}
[11/6/2023, 11:06:22 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 11:06:22 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 11:06:27 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heart


Change Input: Didn't work
[11/6/2023, 11:10:50 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: Live TV, Reference: com.webos.app.livetv
[11/6/2023, 11:10:50 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/6/2023, 11:10:50 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, set Input, Name: HDMI 2, Reference: com.webos.app.hdmi2
[11/6/2023, 11:10:50 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: App: {
  "returnValue": true,
  "id": "com.webos.app.hdmi2",
  "sessionId": "Y29tLndlYm9zLmFwcC5oZG1pMg=="
}
[11/6/2023, 11:10:52 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 11:10:52 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat

Power Off:  Worked, Power On:  Didn't work
[11/6/2023, 11:12:06 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: App: {
  "subscribed": true,
  "appId": "",
  "returnValue": true,
  "windowId": "",
  "processId": ""
}
[11/6/2023, 11:12:06 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true
}
[11/6/2023, 11:12:06 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Unknown power state: undefined
[11/6/2023, 11:12:06 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active",
  "processing": "Request Power Off"
}
[11/6/2023, 11:12:06 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active",
  "processing": "Request Active Standby"
}
[11/6/2023, 11:12:06 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active",
  "processing": "Prepare Active Standby"
}
[11/6/2023, 11:12:06 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Picture: {
  "category": "picture",
  "settings": {
    "contrast": "100",
    "backlight": "80",
    "brightness": "50",
    "color": "60"
  },
  "returnValue": true
}
[11/6/2023, 11:12:07 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 11:12:07 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 11:12:07 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active Standby"
}
[11/6/2023, 11:12:12 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 11:12:12 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 11:12:14 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, set Power: ON
[11/6/2023, 11:12:17 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 11:12:17 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 11:12:22 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 11:12:22 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 11:12:27 AM] [LgWebOsTv] Device: 192.16

**Comment by turbo159** [comment]
I meant to add I don't have volume, mute controls  since I don't use the TV speakers.

**Comment by grzegorz914** [comment]
ok, try 7 screen on off

**Comment by turbo159** [comment]
### Beta7:
ScreenOn: OK
ScreenOff: Failed
InputSwitch: OK
PowerOff: OK
PowerOn: Failed

### Logs:
[11/6/2023, 12:16:59 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "subscribed": true,
  "returnValue": true,
  "state": "Screen Off"
}
[11/6/2023, 12:16:59 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: App: {
  "appId": "com.webos.app.hdmi2",
  "subscribed": true,
  "returnValue": true,
  "windowId": "",
  "processId": ""
}
[11/6/2023, 12:16:59 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Audio: {
  "returnValue": true,
  "volumeMax": 100,
  "ringtonewithvibration": true,
  "scenario": "mastervolume_ext_speaker_optical",
  "hac": false,
  "subscribed": true,
  "volume": -1,
  "action": "requested",
  "supportvolume": false,
  "ringer switch": true,
  "slider": false,
  "active": false,
  "mute": false
}
[11/6/2023, 12:16:59 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Picture: {
  "subscribed": true,
  "category": "picture",
  "settings": {
    "contrast": "100",
    "backlight": 32,
    "brightness": 50,
    "color": "50"
  },
  "returnValue": true
}
[11/6/2023, 12:16:59 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Channel error: {
  "returnValue": false,
  "errorCode": -1000,
  "errorText": "internal error"
}
[11/6/2023, 12:17:00 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/6/2023, 12:17:00 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: HDMI 2, Reference: com.webos.app.hdmi2
[11/6/2023, 12:17:00 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Accessory Name: LGTV.
[11/6/2023, 12:17:00 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Discovery Mode: Always discoverable
[11/6/2023, 12:17:00 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Closed Captions: 0
[11/6/2023, 12:17:00 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Media: STOP
[11/6/2023, 12:17:00 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Target Media: STOP
[11/6/2023, 12:17:00 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Picture Mode: 3
[11/6/2023, 12:17:00 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Mute: OFF
[11/6/2023, 12:17:00 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Volume: 0
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: HDMI 2, Reference: com.webos.app.hdmi2
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Accessory Name: LGTV.
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Discovery Mode: Always discoverable
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Closed Captions: 0
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Media: STOP
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Target Media: STOP
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Picture Mode: 3
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Mute: OFF
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Volume: 0
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:17:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/6/2023, 12:17:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: HDMI 2, Reference: com.webos.app.hdmi2
[11/6/2023, 12:17:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Accessory Name: LGTV.
[11/6/2023, 12:17:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Discovery Mode: Always discoverable
[11/6/2023, 12:17:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Closed Captions: 0
[11/6/2023, 12:17:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Media: STOP
[11/6/2023, 12:17:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Target Media: STOP
[11/6/2023, 12:17:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Picture Mode: 3
[11/6/2023, 12:17:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Mute: OFF
[11/6/2023, 12:17:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Volume: 0
[11/6/2023, 12:17:06 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:06 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:17:11 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:11 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:17:16 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:16 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:17:17 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/6/2023, 12:17:17 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: HDMI 2, Reference: com.webos.app.hdmi2
[11/6/2023, 12:17:17 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Accessory Name: LGTV.
[11/6/2023, 12:17:17 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Discovery Mode: Always discoverable
[11/6/2023, 12:17:17 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Closed Captions: 0
[11/6/2023, 12:17:17 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Media: STOP
[11/6/2023, 12:17:17 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Target Media: STOP
[11/6/2023, 12:17:17 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Picture Mode: 3
[11/6/2023, 12:17:17 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Mute: OFF
[11/6/2023, 12:17:17 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Volume: 0
[11/6/2023, 12:17:18 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/6/2023, 12:17:18 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: HDMI 2, Reference: com.webos.app.hdmi2
[11/6/2023, 12:17:18 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Accessory Name: LGTV.
[11/6/2023, 12:17:18 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Discovery Mode: Always discoverable
[11/6/2023, 12:17:18 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Closed Captions: 0
[11/6/2023, 12:17:18 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Media: STOP
[11/6/2023, 12:17:18 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Target Media: STOP
[11/6/2023, 12:17:18 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Picture Mode: 3
[11/6/2023, 12:17:18 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Mute: OFF
[11/6/2023, 12:17:18 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Volume: 0
[11/6/2023, 12:17:21 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:21 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:17:23 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/6/2023, 12:17:23 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: HDMI 2, Reference: com.webos.app.hdmi2
[11/6/2023, 12:17:23 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Accessory Name: LGTV.
[11/6/2023, 12:17:23 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Discovery Mode: Always discoverable
[11/6/2023, 12:17:23 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Closed Captions: 0
[11/6/2023, 12:17:23 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Media: STOP
[11/6/2023, 12:17:23 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Target Media: STOP
[11/6/2023, 12:17:23 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Picture Mode: 3
[11/6/2023, 12:17:23 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Mute: OFF
[11/6/2023, 12:17:23 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Volume: 0
[11/6/2023, 12:17:26 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:26 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:17:31 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:31 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:17:36 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:36 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:17:41 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:41 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:17:42 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: HDMI 2, Reference: com.webos.app.hdmi2
[11/6/2023, 12:17:42 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/6/2023, 12:17:46 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:46 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:17:50 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen ON.
[11/6/2023, 12:17:50 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Screen Off",
  "processing": "Screen On"
}
[11/6/2023, 12:17:50 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/6/2023, 12:17:50 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/6/2023, 12:17:51 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:51 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:17:55 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/6/2023, 12:17:55 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {
  "returnValue": false,
  "errorText": "Invalid standbyMode !!",
  "errorCode": "POWER_ERROR_0003"
}
[11/6/2023, 12:17:56 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:17:56 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/6/2023, 12:18:05 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: HDMI 2, Reference: com.webos.app.hdmi2
[11/6/2023, 12:18:06 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:06 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:10 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/6/2023, 12:18:10 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: HDMI 2, Reference: com.webos.app.hdmi2
[11/6/2023, 12:18:11 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:11 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:16 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:16 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:20 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/6/2023, 12:18:20 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {
  "returnValue": false,
  "errorText": "Invalid standbyMode !!",
  "errorCode": "POWER_ERROR_0003"
}
[11/6/2023, 12:18:21 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:21 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:26 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:26 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:31 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:31 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:32 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, set Input, Name: HDMI 1, Reference: com.webos.app.hdmi1
[11/6/2023, 12:18:32 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: App: {
  "returnValue": true,
  "id": "com.webos.app.hdmi1",
  "sessionId": "Y29tLndlYm9zLmFwcC5oZG1pMQ=="
}
[11/6/2023, 12:18:32 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: App: {
  "subscribed": true,
  "appId": "com.webos.app.hdmi1",
  "returnValue": true,
  "windowId": "",
  "processId": ""
}
[11/6/2023, 12:18:32 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Picture: {
  "category": "picture",
  "settings": {
    "contrast": "100",
    "backlight": "80",
    "brightness": "50",
    "color": "60"
  },
  "returnValue": true
}
[11/6/2023, 12:18:32 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Picture: {
  "category": "picture",
  "settings": {
    "contrast": "85",
    "backlight": "80",
    "brightness": 50,
    "color": "50"
  },
  "returnValue": true
}
[11/6/2023, 12:18:36 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:36 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:38 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, set Input, Name: HDMI 2, Reference: com.webos.app.hdmi2
[11/6/2023, 12:18:38 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: App: {
  "returnValue": true,
  "id": "com.webos.app.hdmi2",
  "sessionId": "Y29tLndlYm9zLmFwcC5oZG1pMg=="
}
[11/6/2023, 12:18:38 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: App: {
  "subscribed": true,
  "appId": "com.webos.app.hdmi2",
  "returnValue": true,
  "windowId": "",
  "processId": ""
}
[11/6/2023, 12:18:38 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Picture: {
  "category": "picture",
  "settings": {
    "contrast": "100",
    "backlight": "80",
    "brightness": "50",
    "color": "60"
  },
  "returnValue": true
}
[11/6/2023, 12:18:38 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Picture: {
  "category": "picture",
  "settings": {
    "contrast": "100",
    "backlight": 32,
    "brightness": 50,
    "color": "50"
  },
  "returnValue": true
}
[11/6/2023, 12:18:41 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:41 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:43 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, set Power: OFF
[11/6/2023, 12:18:43 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active",
  "processing": "Request Power Off"
}
[11/6/2023, 12:18:43 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active",
  "processing": "Request Active Standby"
}
[11/6/2023, 12:18:43 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active",
  "processing": "Prepare Active Standby"
}
[11/6/2023, 12:18:43 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: App: {
  "subscribed": true,
  "appId": "",
  "returnValue": true,
  "windowId": "",
  "processId": ""
}
[11/6/2023, 12:18:43 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true
}
[11/6/2023, 12:18:43 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Unknown power state: undefined
[11/6/2023, 12:18:43 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Picture: {
  "category": "picture",
  "settings": {
    "contrast": "100",
    "backlight": "80",
    "brightness": "50",
    "color": "60"
  },
  "returnValue": true
}
[11/6/2023, 12:18:44 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active Standby"
}
[11/6/2023, 12:18:46 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:46 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:50 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, set Power: ON
[11/6/2023, 12:18:51 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:51 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:18:56 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:18:56 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:06 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:06 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:07 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active Standby",
  "processing": "Prepare Power On"
}
[11/6/2023, 12:19:07 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active Standby",
  "processing": "LastInput Ready",
  "powerOnReason": "remoteKey"
}
[11/6/2023, 12:19:07 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active Standby",
  "processing": "Screen On"
}
[11/6/2023, 12:19:07 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: App: {
  "subscribed": true,
  "appId": "com.webos.app.hdmi2",
  "returnValue": true,
  "windowId": "",
  "processId": ""
}
[11/6/2023, 12:19:07 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Picture: {
  "category": "picture",
  "settings": {
    "contrast": "100",
    "backlight": 32,
    "brightness": 50,
    "color": "50"
  },
  "returnValue": true
}
[11/6/2023, 12:19:07 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/6/2023, 12:19:11 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:11 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:16 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:16 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:21 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:21 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:26 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:26 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:28 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/6/2023, 12:19:28 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {
  "returnValue": false,
  "errorText": "Invalid standbyMode !!",
  "errorCode": "POWER_ERROR_0003"
}
[11/6/2023, 12:19:31 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:31 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:36 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:36 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:41 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:41 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:42 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen ON.
[11/6/2023, 12:19:42 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {
  "returnValue": false,
  "errorText": "Invalid standbyMode !!",
  "errorCode": "POWER_ERROR_0003"
}
[11/6/2023, 12:19:45 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/6/2023, 12:19:45 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {
  "returnValue": false,
  "errorText": "Invalid standbyMode !!",
  "errorCode": "POWER_ERROR_0003"
}
[11/6/2023, 12:19:46 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:46 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:51 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:51 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:19:56 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:19:56 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:20:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Screen Off"
}
[11/6/2023, 12:20:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:20:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023, 12:20:06 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/6/2023, 12:20:06 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/6/2023,

**Comment by grzegorz914** [comment]
@turbo159 
regarding Power On, are you using docker image?

**Comment by turbo159** [comment]
> @turbo159 regarding Power On, are you using docker image?

Yes, I am using: homebridge/homebridge:latest

**Comment by grzegorz914** [comment]
https://www.devwithimagination.com/2020/06/15/homebridge-docker-and-wake-on-lan/

**Comment by turbo159** [comment]
Ok, I will take a look.  For me, the feature I really want to control from HomeKit is the ScreenOn/Off.  Is that affected by running in docker too?

**Comment by grzegorz914** [comment]
no, screen on off is other thing

**Comment by turbo159** [comment]
Beta v2.14.1-beta.27

ScreenOn:  OK
ScreenOff:  Failed

Logs:
[11/7/2023, 9:11:51 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen ON.
[11/7/2023, 9:11:51 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Screen Off",
  "processing": "Screen On"
}
[11/7/2023, 9:11:51 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/7/2023, 9:11:51 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/7/2023, 9:11:55 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 9:11:55 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 9:11:59 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/7/2023, 9:11:59 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {
  "returnValue": false,
  "errorText": "Invalid standbyMode !!",
  "errorCode": "POWER_ERROR_0003"
}
[11/7/2023, 9:12:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 9:12:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 9:12:05 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, d

**Comment by turbo159** [comment]
Beta: v2.14.1-beta29

ScreenOn: OK
- Turned on, but the tile on the control center still showed off.
- Going into the HomeKit app from the control center, then the tile showed on.
ScreenOff:  Failed

Logs:
[11/7/2023, 10:13:57 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/7/2023, 10:13:57 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: Live TV, Reference: com.webos.app.livetv
[11/7/2023, 10:14:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen ON.
[11/7/2023, 10:14:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 10:14:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 10:14:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Screen Off",
  "processing": "Screen On"
}
[11/7/2023, 10:14:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/7/2023, 10:14:00 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/7/2023, 10:14:05 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 10:14:05 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 10:14:10 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 10:14:10 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 10:14:12 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Input, Name: Live TV, Reference: com.webos.app.livetv
[11/7/2023, 10:14:12 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Power: ON
[11/7/2023, 10:14:15 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 10:14:15 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 10:14:20 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 10:14:20 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 10:14:21 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/7/2023, 10:14:21 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Received error message: {
  "returnValue": false,
  "errorText": "Invalid standbyMode !!",
  "errorCode": "POWER_ERROR_0003"
}
[11/7/2023, 10:14:25 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 10:14:25 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 10:14:30 AM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 10:14:30 AM

**Comment by turbo159** [comment]
Beta 31:

ScreenOn:  Failed
ScreenOff: Failed

[11/7/2023, 3:10:35 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen ON.
[11/7/2023, 3:10:35 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {
  "returnValue": false,
  "errorText": "Invalid standbyMode !!",
  "errorCode": "POWER_ERROR_0003"
}
[11/7/2023, 3:10:37 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 3:10:37 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 3:10:40 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/7/2023, 3:10:40 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {
  "returnValue": false,
  "errorText": "Invalid standbyMode !!",
  "errorCode": "POWER_ERROR_0003"
}
[11/7/2023, 3:10:40 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen ON.
[11/7/2023, 3:10:40 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {
  "returnValue": false,
  "errorText": "Invalid standbyMode !!",
  "errorCode": "POWER_ERROR_0003"
}
[11/7/2023, 3:10:42 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Screen Off",
  "processing": "Screen On"
}
[11/7/2023, 3:10:42 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/7/2023, 3:10:42 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 3:10:42 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 3:10:47 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 3:10:47 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 3:10:48 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/7/2023, 3:10:48 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {
  "returnValue": false,
  "errorText": "Invalid standbyMode !!",
  "errorCode": "POWER_ERROR_0003"
}
[11/7/2023, 3:10:52 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 3:10:52 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 3:10:57 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 3:10:57 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 3:11:01 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Screen Off"
}
[11/7/2023, 3:11:02 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 3:11:02 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 3:11:07 P

**Comment by turbo159** [comment]
Beta 32

ScreenOn:  OK
ScreenOff: Failed

[11/7/2023, 4:26:57 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen ON.
[11/7/2023, 4:26:57 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Screen Off",
  "processing": "Screen On"
}
[11/7/2023, 4:26:57 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/7/2023, 4:26:57 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power: {
  "returnValue": true,
  "state": "Active"
}
[11/7/2023, 4:26:57 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 4:26:58 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 4:27:02 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 4:27:03 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 4:27:04 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, Turn Screen OFF.
[11/7/2023, 4:27:04 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Power error: {}
[11/7/2023, 4:27:07 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 4:27:08 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked received heartbeat.
[11/7/2023, 4:27:13 PM] [LgWebOsTv] Device: 192.168.20.128 LGTV, debug: Socked send heartbeat.
[11/7/2023, 4:27:13 PM] [LgWebOsTv] Device: 19

**Comment by badgertastic** [comment]
can we have screen on/off reinstated as per 12.13.4 please

**Comment by grzegorz914** [comment]
try 2.14.5-beta.1 and let me know

**Comment by badgertastic** [comment]
> try 2.14.5-beta.1 and let me know

Resolved, thanks :)

**Comment by turbo159** [comment]
Just an fyi.  Even with these new versions the Screen On/Off still doesn't work for me.  However, I tried [Merdok](https://github.com/merdok/homebridge-webos-tv) fork, and it does work.  I don't know what the difference is and I'm not criticizing you.  Just letting you know so that maybe you can incorporate what Merdok is doing too.

Thanks.

**Comment by grzegorz914** [comment]
@turbo159 which version was working for you?

**Comment by turbo159** [comment]
> @turbo159 which version was working for you?
![image](https://github.com/grzegorz914/homebridge-lgwebos-tv/assets/25274813/54c28c3e-6b21-4333-a88c-00f0f39d19f0)

**Comment by grzegorz914** [comment]
Try latest release

**Comment by turbo159** [comment]
I tried, but for some reason I couldn't add it to home kit.  It wouldn't show up even after entering the code.
